### PR TITLE
Fill README.md with information about the project and add the kata in…

### PR DESCRIPTION
**Pull request by natiitl**
Modify file README.md with information about the project and add the kata information. For a issue #2

### CODE REVIEW

**Review by mbarriolifull — CHANGES_REQUESTED** [review]
README needs to explain how to properly build the project, its testing framework, the language, or any specific file structure (ex: why the .idea directory is created and from where)

**Review by PolSM95 — CHANGES_REQUESTED** [review]
You probably need to add more information about all the dependencies and plugins that needs the project to build it. For example, the JUnit version, the project structure and the language used.

**Comment by natiitl** [comment]
Gracias por la aportación. Los cambios ya han sido realizado.

**Review by mbarriolifull — CHANGES_REQUESTED** [review]
Please Check the Java and JUnit version, seems to be interchanged.

**Review by PolSM95 — CHANGES_REQUESTED** [review]
Check the versions, they're probably flipped

**Comment by natiitl** [comment]
Ya hemos realizado el cambio

**Review by mbarriolifull — APPROVED** [review]

**Review by PolSM95 — APPROVED** [review]

**Pull request merged**
